[package]
name = "twine"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
once_cell = { version = "1.19.0", default-features = false, features = [ "std" ] }
scraper = { version = "0.18.1", default-features = false }
thiserror = "1.0.56"
